### ISSUE TITLE
Do you sponsor open source organization? 

### ISSUE THREAD

**Issue by caniszczyk** [todogroup/survey#10]
What is your company budget to sponsor open source organizations

**Comment by DuaneOBrien** [comment]
Do we include conferences here?

**Comment by LawrenceHecht** [comment]
> What is your motivation to sponsor organizations? goodwill, sustainability, outcomes etc

Is there a set of specific criteria that the Linux Foundation has used in its internal market research?

I think people will likely say that everything is a motivation. I'm mostly interested in: 1) recruitment; 2) support and training

**Comment by LawrenceHecht** [comment]
> Do we include conferences here?

I think conferences/events are a separate thing, but I am suggesting that they should be included in a question about the rationale for sponsoring these orgs.

**Comment by LawrenceHecht** [comment]
> What is your company budget to sponsor open source organizations

Instead of asking about budget, ask about how much the company is expected to spend in 2019. That way, unbudgeted money will be included in the answer.

I also want to know if we are only talking about organizations that are foundations or non-profits. What about groups where there is no formal organization or when the money goes to an individual to support a project?

**Comment by caniszczyk** [comment]
fixed https://github.com/todogroup/survey/pull/33
