### ISSUE TITLE
Do people know what an OSPO is?

### ISSUE THREAD

**Issue by vmbrasseur** [todogroup/survey#40]
Feedback from the TODO Group meeting 2019-09:

Ask people whether they know/are familiar with what an OSPO is (and include a definition of it).

**Comment by LawrenceHecht** [comment]
@vmbrasseur 1) We originally didn't include a definition so we didn't bias the question about what a program's responsibilities are. 2) We know that among those that don't have plans for an open source program, only 21% said that it is because they were unfamiliar with the term. 3)I am adding this to a list of suggestions I'm compiling.

**Comment by vmbrasseur** [comment]
The question wasn't mine. It came up in the TODO Group meeting. I simply was the scribe who captured it in an issue so it wouldn't be forgotten later on.
